steps:
  - id: "Inicio Cloud Build A"
    name: alpine
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # Autenticarse con GCP
        echo "Iniciado despliegue"
        echo "rama $BRANCH_NAME"
        echo "Repositorio: $REPO_NAME"
        echo "Commit: $COMMIT_SHA"
        ls -la
  
  - id: "Consolidar config y subir al bucket"
    name: python
    entrypoint: python3
    args: ["src/tools/build_config.py"]

  - id: "Activar Cloud Build B"
    name: gcr.io/cloud-builders/git
    entrypoint: "sh"
    args:
      - -c
      - |
        echo "Iniciando git clone"
        git clone --depth=1000 https://github.com/jesusCotrina/02-framework-scraping-HR.git repo
        cd repo
        echo "Obteniendo archivos modificados..."
        chaged_files=$(git show --name-only --pretty="" $COMMIT_SHA)

        echo "Archivos detectados:"
        echo "$chaged_files"

        echo "=== 1) Detectando carpetas únicas dentro de src/cloud-run-scraping ==="

        modified_folders=$(echo "$chaged_files" | grep "^src/cloud-run-scraping/" \
          | cut -d'/' -f3 \
          | sort -u)

        echo "Carpetas modificadas:"
        echo "$modified_folders"

        if [ -z "$modified_folders" ]; then
          echo "No hay carpetas modificadas."
          exit 0
        fi

        echo "" > /workspace/folders_detected.env

        for folder in $modified_folders; do
          echo "Procesando carpeta: $folder"

          echo "=== 2) Detectando tipo de cambio (src | config | ambos) ==="

          # Filtrar archivos solo de esta carpeta
          files_in_folder=$(echo "$chaged_files" | grep "src/cloud-run-scraping/${folder}")
          echo "files in folder: ${files_in_folder}"
          changed_src=$(echo "$files_in_folder" | grep "/src/" || true)
          changed_config=$(echo "$files_in_folder" | grep "/config/" || true)

          if [ -n "$changed_src" ]; then
              type="image"
          else
              type="terraform"
          fi

          echo "Tipo detectado para $folder: $type"

          echo "=== 3) Extrayendo código ==="
          # Ejemplo folder = cr-scrp-10-clinica-internacional → code=10
          code=$(echo "$folder" | sed -E 's/cr-scrp-([0-9]+).*/\1/')
          echo "Código extraído: $code"

          echo "FOLDER_$code=\"$folder\""    
          echo "CODE_$code=\"$code\""        
          echo "type_$code=\"$type\"" 
          echo "activando cloud run"        
          gcloud builds triggers run "deploy-frmk-scraping-infra-trrfm-dev" \
          --region=us-east4 \
          --branch="$BRANCH_NAME" \
          --substitutions=_CODE_IMAGE="$code",_PATH_GCR="$folder",_DPLOY_TYPE="$type"

          echo "-----------------------------------------------"

        done

        
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-east4"
  _PROJECT_ID: "data-engineer-410822"
